services:
  - type: web
    name: kr-question-generator-backend
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: uvicorn server.app_local:app --host 0.0.0.0 --port 4000
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
